version: '3'

tasks:
  setup:
    desc: Create Python virtual environment
    cmds:
      - uv venv

  install:
    desc: Install package in development mode
    deps: [setup]
    cmds:
      - uv pip install -e ".[dev]"

  format:
    desc: Format code using ruff
    cmds:
      - .venv/bin/ruff format src tests

  check:
    desc: Check and auto-fix code using ruff
    cmds:
      - .venv/bin/ruff check --fix src tests

  test:
    desc: Run tests
    cmds:
      - .venv/bin/pytest tests

  test-cov:
    desc: Run tests with coverage
    cmds:
      - .venv/bin/pytest tests --cov=zephyr_mcp --cov-report=term-missing --cov-report=html
